//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeBook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public int ID { get; set; }
        public int IDucenika { get; set; }
        public int IDrubrike { get; set; }
        public Nullable<short> ocjena1 { get; set; }
        public string biljeska { get; set; }
        public Nullable<System.DateTime> vrijemeUnosa { get; set; }
    
        public virtual Rubrika Rubrika { get; set; }
        public virtual Ucenik Ucenik { get; set; }
    }
}
