//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeBook.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class risEntities : DbContext
    {
        public risEntities()
            : base("name=risEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Obavijesti> Obavijesti { get; set; }
        public virtual DbSet<Ocjena> Ocjena { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Razred> Razred { get; set; }
        public virtual DbSet<Rubrika> Rubrika { get; set; }
        public virtual DbSet<Skola> Skola { get; set; }
        public virtual DbSet<Smjer> Smjer { get; set; }
        public virtual DbSet<TipZaposlenika> TipZaposlenika { get; set; }
        public virtual DbSet<Ucenik> Ucenik { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
