//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeBook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucenik()
        {
            this.Ocjena = new HashSet<Ocjena>();
        }
    
        public int ID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datumRodjenja { get; set; }
        public string oib { get; set; }
        public string brojTelefona { get; set; }
        public string brojMobitela { get; set; }
        public int razred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjena> Ocjena { get; set; }
        public virtual Razred Razred1 { get; set; }
    }
}
